services:
  mysql:
    image: 'mysql:latest'
    container_name: local-mysql
    command: ["--skip-name-resolve"]
    environment:
      - 'MYSQL_DATABASE=ciphergate'
      - 'MYSQL_PASSWORD=Jx4zx_aYui23'
      - 'MYSQL_ROOT_PASSWORD=super_axUobn34U'
      - 'MYSQL_USER=kersin'
    ports:
      - '13306:3306'

  minio:
    image: 'minio/minio:latest'
    container_name: local-minio
    environment:
      - 'MINIO_ROOT_USER=ciphergate_minio'
      - 'MINIO_ROOT_PASSWORD=ciphergate_minio123'
    command: server /data --console-address ":9001"
    ports:
      - '19000:9000'
      - '19001:9001'

  redis:
    image: 'redis:7-alpine'
    container_name: local-redis
    command: [ "redis-server", "--appendonly", "yes" ]
    ports:
      - '16379:6379'

  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: local-rabbitmq
    environment:
      - 'RABBITMQ_DEFAULT_USER=ciphergate'
      - 'RABBITMQ_DEFAULT_PASS=ciphergate_rabbit123'
    ports:
      - '5672:5672'
      - '15672:15672'
